#GSmart Application Configuration
#Thu Jul 17 17:27:28 GMT-03:00 2025
db.url=jdbc\:postgresql\://localhost\:5432/seu_banco
db.user=postgres
powerbi.url=https\://api.powerbi.com/beta/f06a7122-3027-4312-b120-38f60897fba4/datasets/718c30e8-7661-4cb4-a9d6-9ec086369748/rows?experience\=power-bi&key\=z1MN83xflFWMuo%2FS7%2FWqSpgq1S6SylF4X%2BiuXvLkVXMItKSqUMOTn1LS0tIVuaBRyV0XMWJUy9KMopholiSTUQ%3D%3D 
source.last=Thingsboard API
telegram.chat_id=\ 7100310686
telegram.token=7642087424\:AAHe42edx2LcrBTUmv5neKEcPxQRM1xZLq4 
thingsboard.url=http\://10.5.0.80\:8080
