#GSmart Application Configuration
#Mon Jun 30 16:18:53 GMT-03:00 2025
db.url=jdbc\:postgresql\://localhost\:5432/seu_banco
db.user=postgres
logic.run=false
powerbi.url=https\://api.powerbi.com/beta/f06a7122-3027-4312-b120-38f60897fba4/datasets/718c30e8-7661-4cb4-a9d6-9ec086369748/rows?experience\=power-bi&key\=z1MN83xflFWMuo%2FS7%2FWqSpgq1S6SylF4X%2BiuXvLkVXMItKSqUMOTn1LS0tIVuaBRyV0XMWJUy9KMopholiSTUQ%3D%3D
source.last=Thingsboard API
thingsboard.url=http\://10.5.0.80\:8080
