#GSmart Application Configuration
#Fri Jul 25 14:04:47 GMT-03:00 2025
db.url=jdbc\:postgresql\://localhost\:5432/seu_banco
db.user=postgres
mqtt.broker.url=tcp\://10.5.0.11\:1883
powerbi.url=https\://api.powerbi.com/beta/f06a7122-3027-4312-b120-38f60897fba4/datasets/b8512173-e419-4a24-9559-2f9f52935190/rows?experience\=power-bi&key\=%2F7U6mAvLW4ddN8tfVZJfT30CTl6LGrU4wmW%2FdotkmHnoj5eaVfUZh9fzlWFCgFnsSWI55MecpelCBmyb9reDpw%3D%3D
source.last=Thingsboard API
telegram.chat_id=-1002829690693
telegram.token=7642087424\:AAHe42edx2LcrBTUmv5neKEcPxQRM1xZLq4
thingsboard.url=http\://10.8.0.5\:8080
